// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  tutorialSidebar: [
    {
      type: 'doc',
      id: 'introduction',
      label: 'Overview',
    },
    {
      type: 'category',
      label: 'Confidential Computing',
      items: [
        { type: 'autogenerated', dirName: 'Confidential Computing' },
      ],
    },
    {
      type: 'category',
      label: 'Kubernetes Integration',
      link: { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-install-infra' },
      items: [
        { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-deploy-kubernetes', label: 'Deploy Kubernetes for a local deployment' },
        { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-install-3rd-party', label: 'Install third-party components' },
        { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-log', label: 'Troubleshoot deployments and view Kubernetes logs' },
        { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-deploy-troubleshooting', label: 'Maintain and troubleshoot a local deployment' },
        { type: 'doc', id: 'kubernetes/Kubernetes installation/pkg-trouble', label: 'Troubleshoot a local Kubernetes deployment' },
      ],
    },
    {
      type: 'category',
      label: 'Operation Guide',
      link: { type: 'doc', id: 'symplified/Operation Guide/operations-guide' },
      items: [
        { type: 'doc', id: 'symplified/Operation Guide/idenity-routers', label: 'Identity Routers Operations Guide' },
        { type: 'doc', id: 'symplified/Operation Guide/idr-administrators', label: 'Identity Router Administrators' },
        { type: 'doc', id: 'symplified/Operation Guide/customers', label: 'Create/Edit Customers' },
        { type: 'doc', id: 'symplified/Operation Guide/application-types', label: 'My Application Types' },
        { type: 'doc', id: 'symplified/Operation Guide/handlers', label: 'Identity Router Handlers' },
        { type: 'doc', id: 'symplified/Operation Guide/certificates', label: 'Identity Routers Certificates' },
        { type: 'doc', id: 'symplified/Operation Guide/amazon-ec2', label: 'Amazon EC2 Identity Router Deployment' },
        { type: 'doc', id: 'symplified/Operation Guide/ad-federation-services', label: 'Active Directory Federation Services' },
        { type: 'doc', id: 'symplified/Operation Guide/edit -profile', label: 'Edit Profile Information' },
        { type: 'doc', id: 'Reference/idr-api-reference', label: 'Identity Router API reference' },
      ],
    },
  ],
};

export default sidebars;
